// Mock data for Phase A - Core Item Screens
// All data is hardcoded. Will be replaced with API calls later.

export const mockCategories = [
    'Electronics',
    'Documents',
    'Clothing',
    'Accessories',
    'Books',
    'Bags',
    'Keys',
    'Wallets',
    'Other',
];

export const mockSchools = [
    { id: '1', name: 'Cebu Institute of Technology - University', shortName: 'CIT-U', emailDomain: 'cit.edu' },
    { id: '2', name: 'University of San Carlos', shortName: 'USC', emailDomain: 'usc.edu.ph' },
    { id: '3', name: 'University of the Philippines Cebu', shortName: 'UP Cebu', emailDomain: 'up.edu.ph' },
    { id: '4', name: 'University of San Jose-Recoletos', shortName: 'USJ-R', emailDomain: 'usjr.edu.ph' },
    { id: '5', name: 'University of Cebu', shortName: 'UC', emailDomain: 'uc.edu.ph' },
    { id: '6', name: 'Southwestern University PHINMA', shortName: 'SWU', emailDomain: 'swu.edu.ph' },
    { id: '7', name: 'Cebu Normal University', shortName: 'CNU', emailDomain: 'cnu.edu.ph' },
    { id: '8', name: 'Cebu Technological University', shortName: 'CTU', emailDomain: 'ctu.edu.ph' },
];

export const mockItems = [
    {
        id: '1',
        type: 'LOST',
        title: 'Black Samsung Galaxy S24',
        description: 'Lost near CIT-U library, 2nd floor. It has a dark blue case with a small crack on the top right corner. Last seen around 2:30 PM near the study tables.',
        category: 'Electronics',
        status: 'ACTIVE',
        imageUrl: 'https://picsum.photos/seed/phone1/400/300',
        postedBy: { id: 'u1', firstName: 'Juan', lastName: 'Dela Cruz', school: { shortName: 'CIT-U' } },
        school: { id: '1', name: 'Cebu Institute of Technology - University', shortName: 'CIT-U' },
        locationDescription: 'CIT-U Main Library, 2nd Floor',
        createdAt: '2025-02-20T10:30:00',
        expiresAt: '2025-03-22T10:30:00',
        claimCount: 2,
    },
    {
        id: '2',
        type: 'FOUND',
        title: 'Blue Umbrella with Wooden Handle',
        description: 'Found this umbrella left behind in Room 301 after the 4PM class. It is navy blue with a curved wooden handle.',
        category: 'Accessories',
        status: 'ACTIVE',
        imageUrl: 'https://picsum.photos/seed/umbrella1/400/300',
        postedBy: { id: 'u2', firstName: 'Maria', lastName: 'Santos', school: { shortName: 'USC' } },
        school: { id: '2', name: 'University of San Carlos', shortName: 'USC' },
        locationDescription: 'USC Bunzel Building, Room 301',
        createdAt: '2025-02-21T14:15:00',
        expiresAt: '2025-03-23T14:15:00',
        claimCount: 0,
    },
    {
        id: '3',
        type: 'LOST',
        title: 'Silver MacBook Pro 14"',
        description: 'Left my laptop in the computer lab. Silver MacBook Pro with a "UP Fighting Maroons" sticker on the back. Has my thesis files — please help!',
        category: 'Electronics',
        status: 'ACTIVE',
        imageUrl: 'https://picsum.photos/seed/laptop1/400/300',
        postedBy: { id: 'u3', firstName: 'Carlo', lastName: 'Reyes', school: { shortName: 'UP Cebu' } },
        school: { id: '3', name: 'University of the Philippines Cebu', shortName: 'UP Cebu' },
        locationDescription: 'UP Cebu Computer Lab, Room 204',
        createdAt: '2025-02-19T09:00:00',
        expiresAt: '2025-03-21T09:00:00',
        claimCount: 1,
    },
    {
        id: '4',
        type: 'FOUND',
        title: 'Student ID Card - USJ-R',
        description: 'Found a USJ-R student ID card on the ground near the main gate. The card looks relatively new.',
        category: 'Documents',
        status: 'CLAIMED',
        imageUrl: 'https://picsum.photos/seed/id1/400/300',
        postedBy: { id: 'u4', firstName: 'Ana', lastName: 'Garcia', school: { shortName: 'USJ-R' } },
        school: { id: '4', name: 'University of San Jose-Recoletos', shortName: 'USJ-R' },
        locationDescription: 'USJ-R Basak Campus Main Gate',
        createdAt: '2025-02-18T16:45:00',
        expiresAt: '2025-03-20T16:45:00',
        claimCount: 3,
    },
    {
        id: '5',
        type: 'LOST',
        title: 'Red JanSport Backpack',
        description: 'Left my red JanSport backpack in the cafeteria. It has my notebooks, a water bottle, and a small pencil case inside. There is a keychain of a cat attached to the zipper.',
        category: 'Bags',
        status: 'ACTIVE',
        imageUrl: 'https://picsum.photos/seed/bag1/400/300',
        postedBy: { id: 'u5', firstName: 'Miguel', lastName: 'Torres', school: { shortName: 'UC' } },
        school: { id: '5', name: 'University of Cebu', shortName: 'UC' },
        locationDescription: 'UC Main Campus Cafeteria',
        createdAt: '2025-02-22T12:00:00',
        expiresAt: '2025-03-24T12:00:00',
        claimCount: 0,
    },
    {
        id: '6',
        type: 'FOUND',
        title: 'Set of Keys with Toyota Keychain',
        description: 'Found a set of 4 keys on a ring with a Toyota logo keychain near the parking area. One key looks like a house key.',
        category: 'Keys',
        status: 'ACTIVE',
        imageUrl: 'https://picsum.photos/seed/keys1/400/300',
        postedBy: { id: 'u6', firstName: 'Patricia', lastName: 'Lim', school: { shortName: 'SWU' } },
        school: { id: '6', name: 'Southwestern University PHINMA', shortName: 'SWU' },
        locationDescription: 'SWU Parking Area B',
        createdAt: '2025-02-23T08:30:00',
        expiresAt: '2025-03-25T08:30:00',
        claimCount: 1,
    },
    {
        id: '7',
        type: 'LOST',
        title: 'Brown Leather Wallet',
        description: 'Lost my brown leather wallet somewhere between the Engineering building and the gym. Contains my ID and some cash. Brand is Herschel.',
        category: 'Wallets',
        status: 'ACTIVE',
        imageUrl: 'https://picsum.photos/seed/wallet1/400/300',
        postedBy: { id: 'u1', firstName: 'Juan', lastName: 'Dela Cruz', school: { shortName: 'CIT-U' } },
        school: { id: '1', name: 'Cebu Institute of Technology - University', shortName: 'CIT-U' },
        locationDescription: 'CIT-U Engineering Building to Gym pathway',
        createdAt: '2025-02-23T15:20:00',
        expiresAt: '2025-03-25T15:20:00',
        claimCount: 0,
    },
    {
        id: '8',
        type: 'FOUND',
        title: 'TI-84 Plus Calculator',
        description: 'Found a Texas Instruments TI-84 Plus graphing calculator left in Room 105 after a Math exam. It has a name written on the back in marker but it is partially faded.',
        category: 'Electronics',
        status: 'ACTIVE',
        imageUrl: 'https://picsum.photos/seed/calc1/400/300',
        postedBy: { id: 'u7', firstName: 'Lea', lastName: 'Villanueva', school: { shortName: 'CNU' } },
        school: { id: '7', name: 'Cebu Normal University', shortName: 'CNU' },
        locationDescription: 'CNU Room 105',
        createdAt: '2025-02-22T17:00:00',
        expiresAt: '2025-03-24T17:00:00',
        claimCount: 0,
    },
    {
        id: '9',
        type: 'LOST',
        title: 'Prescription Eyeglasses',
        description: 'Lost my prescription eyeglasses in a black hard case. The frames are dark tortoiseshell pattern. I really need these for class!',
        category: 'Accessories',
        status: 'HANDED_OVER',
        imageUrl: 'https://picsum.photos/seed/glasses1/400/300',
        postedBy: { id: 'u8', firstName: 'Daniel', lastName: 'Tan', school: { shortName: 'CTU' } },
        school: { id: '8', name: 'Cebu Technological University', shortName: 'CTU' },
        locationDescription: 'CTU Main Building Hallway',
        createdAt: '2025-02-15T11:00:00',
        expiresAt: '2025-03-17T11:00:00',
        claimCount: 1,
    },
    {
        id: '10',
        type: 'FOUND',
        title: 'Nursing Textbook - Fundamentals',
        description: 'Found a "Fundamentals of Nursing" textbook by Kozier & Erb, 11th edition, left on a bench near the SWU chapel. Has some highlighted pages.',
        category: 'Books',
        status: 'ACTIVE',
        imageUrl: 'https://picsum.photos/seed/book1/400/300',
        postedBy: { id: 'u6', firstName: 'Patricia', lastName: 'Lim', school: { shortName: 'SWU' } },
        school: { id: '6', name: 'Southwestern University PHINMA', shortName: 'SWU' },
        locationDescription: 'SWU Chapel Area Bench',
        createdAt: '2025-02-21T09:45:00',
        expiresAt: '2025-03-23T09:45:00',
        claimCount: 0,
    },
    {
        id: '11',
        type: 'LOST',
        title: 'White Nike Air Force 1 (Left Shoe)',
        description: 'Somehow lost my left Nike Air Force 1 shoe near the USC gym locker area. Size 10 mens. It was in a plastic bag.',
        category: 'Clothing',
        status: 'EXPIRED',
        imageUrl: 'https://picsum.photos/seed/shoe1/400/300',
        postedBy: { id: 'u2', firstName: 'Maria', lastName: 'Santos', school: { shortName: 'USC' } },
        school: { id: '2', name: 'University of San Carlos', shortName: 'USC' },
        locationDescription: 'USC Gym Locker Area',
        createdAt: '2025-01-10T13:00:00',
        expiresAt: '2025-02-09T13:00:00',
        claimCount: 0,
    },
    {
        id: '12',
        type: 'FOUND',
        title: 'USB Flash Drive 64GB',
        description: 'Found a black SanDisk 64GB USB flash drive plugged into one of the library computers. It was still inserted when I sat down.',
        category: 'Electronics',
        status: 'ACTIVE',
        imageUrl: 'https://picsum.photos/seed/usb1/400/300',
        postedBy: { id: 'u3', firstName: 'Carlo', lastName: 'Reyes', school: { shortName: 'UP Cebu' } },
        school: { id: '3', name: 'University of the Philippines Cebu', shortName: 'UP Cebu' },
        locationDescription: 'UP Cebu Library, Computer Station 8',
        createdAt: '2025-02-24T10:00:00',
        expiresAt: '2025-03-26T10:00:00',
        claimCount: 0,
    },
    {
        id: '13',
        type: 'LOST',
        title: 'National Bookstore Gift Card',
        description: 'Lost a National Bookstore gift card worth PHP 500 inside a small white envelope. Dropped it somewhere near the UC canteen.',
        category: 'Other',
        status: 'CANCELLED',
        imageUrl: 'https://picsum.photos/seed/gift1/400/300',
        postedBy: { id: 'u5', firstName: 'Miguel', lastName: 'Torres', school: { shortName: 'UC' } },
        school: { id: '5', name: 'University of Cebu', shortName: 'UC' },
        locationDescription: 'UC Main Canteen Area',
        createdAt: '2025-02-17T10:30:00',
        expiresAt: '2025-03-19T10:30:00',
        claimCount: 0,
    },
    {
        id: '14',
        type: 'FOUND',
        title: 'Denim Jacket with Patches',
        description: 'Found a dark denim jacket with various band patches (Nirvana, Arctic Monkeys) draped over a chair in the CTU student lounge. Looks well-loved.',
        category: 'Clothing',
        status: 'ACTIVE',
        imageUrl: 'https://picsum.photos/seed/jacket1/400/300',
        postedBy: { id: 'u8', firstName: 'Daniel', lastName: 'Tan', school: { shortName: 'CTU' } },
        school: { id: '8', name: 'Cebu Technological University', shortName: 'CTU' },
        locationDescription: 'CTU Student Lounge',
        createdAt: '2025-02-24T07:15:00',
        expiresAt: '2025-03-26T07:15:00',
        claimCount: 0,
    },
    {
        id: '15',
        type: 'LOST',
        title: 'AirPods Pro (2nd Gen)',
        description: 'Lost my AirPods Pro in the white charging case. The case has a small scratch on the lid. Last had them in the CNU College of Arts building during my 1PM class.',
        category: 'Electronics',
        status: 'ACTIVE',
        imageUrl: 'https://picsum.photos/seed/airpods1/400/300',
        postedBy: { id: 'u7', firstName: 'Lea', lastName: 'Villanueva', school: { shortName: 'CNU' } },
        school: { id: '7', name: 'Cebu Normal University', shortName: 'CNU' },
        locationDescription: 'CNU College of Arts Building',
        createdAt: '2025-02-23T13:30:00',
        expiresAt: '2025-03-25T13:30:00',
        claimCount: 0,
    },
];

// Helper: calculate "time ago" from a date string
export function timeAgo(dateString) {
    const now = new Date();
    const date = new Date(dateString);
    const seconds = Math.floor((now - date) / 1000);

    if (seconds < 60) return 'Just now';
    const minutes = Math.floor(seconds / 60);
    if (minutes < 60) return `${minutes}m ago`;
    const hours = Math.floor(minutes / 60);
    if (hours < 24) return `${hours}h ago`;
    const days = Math.floor(hours / 24);
    if (days < 7) return `${days}d ago`;
    const weeks = Math.floor(days / 7);
    if (weeks < 4) return `${weeks}w ago`;
    const months = Math.floor(days / 30);
    return `${months}mo ago`;
}

// Helper: calculate days until expiry
export function daysUntilExpiry(expiresAt) {
    const now = new Date();
    const expiry = new Date(expiresAt);
    const days = Math.ceil((expiry - now) / (1000 * 60 * 60 * 24));
    return days > 0 ? days : 0;
}
