export const ROLES = {
    STUDENT: 'STUDENT',
    ADMIN: 'ADMIN',
};

export const ACCOUNT_STATUS = {
    ACTIVE: 'ACTIVE',
    SUSPENDED: 'SUSPENDED',
    DEACTIVATED: 'DEACTIVATED',
};

export const ITEM_STATUS = {
    ACTIVE: 'ACTIVE',
    CLAIMED: 'CLAIMED',
    PENDING_OWNER_CONFIRMATION: 'PENDING_OWNER_CONFIRMATION',
    RETURNED: 'RETURNED',
    EXPIRED: 'EXPIRED',
    TURNED_OVER_TO_OFFICE: 'TURNED_OVER_TO_OFFICE',
    HIDDEN: 'HIDDEN',
    HANDED_OVER: 'HANDED_OVER', // legacy
};

export const CLAIM_STATUS = {
    PENDING: 'PENDING',
    ACCEPTED: 'ACCEPTED',
    REJECTED: 'REJECTED',
    CANCELLED: 'CANCELLED',
    COMPLETED: 'COMPLETED',
    HANDED_OVER: 'HANDED_OVER', // legacy
};
